# Welcome to Jekyll!

# Website settings
title: "Adish"
description: "Personal page using Jack's JalPC Jekyll theme"
keywords: "Adish,Jain,Berkeley,github,gh-page"
baseurl: "/homepage/"

url: "https://adish-jain.github.io"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Adish Jain'
  first_name: 'Jain'
  last_name: 'Adish'
  email: 'adish.jain@berkeley.edu'
  facebook_username: 
  github_username: 'adish-jain'
  twitter_username: 
  avatar: 'static/img/landing/_DEJ2663.jpg'
  desc: 'Dog Lover| An Avid Throner | Intrigued By Numbers | Golden Bear Class of 2020'
# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  name: 'adish-jain'
  #public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
bshare:
        #uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  # uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
        #id: UA-73784599-1

# growingIO
gio:
        #id: a49d4901c7853da9

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
